import type {
  AgentPrompt,
  InstagramInboxProvision,
  IntentNode,
  MemoryItem,
  ProfileInsight,
  Project,
  TasteNode,
  UserProfile,
} from './types';

const now = '2026-06-29T09:00:00.000Z';
const userId = 'demo_user';

export const demoMemoryItems: MemoryItem[] = [
  {
    id: 'mem_instagram_inbox_dm',
    userId,
    type: 'social',
    platform: 'instagram',
    sourceUrl: 'https://instagram.com/reel/private-ai-memory',
    title: 'DM to Recall inbox about private AI memory',
    creator: 'instagram:demo_sender',
    rawContent: 'RCL-MANAZ-9Q2 https://instagram.com/reel/private-ai-memory This is exactly the future agent UX I want.',
    transcript: '',
    extractedText: '',
    summary: 'A high-intent Instagram DM capture showing the user wants agent memory to feel as easy as messaging a person.',
    reasonSaved: 'Sent directly to the Recall Instagram inbox.',
    userNote: 'This is exactly the future agent UX I want.',
    tags: ['demo', 'instagram-inbox', 'high-intent-save'],
    topics: ['AI agents', 'personal memory', 'Instagram inbox capture'],
    values: ['Autonomy', 'Low-friction capture', 'Privacy'],
    emotions: ['clarity', 'excitement'],
    aesthetics: ['native messaging UX'],
    people: [],
    tools: ['Instagram Messaging API', 'Recall Inbox'],
    projects: ['Recall'],
    traitsSuggested: ['captures in the flow of life', 'future-facing builder'],
    importanceScore: 95,
    profileImpactScore: 92,
    confidence: 0.88,
    status: 'added_to_profile',
    sensitive: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mem_ai_agents_reel',
    userId,
    type: 'social',
    platform: 'instagram',
    sourceUrl: 'https://instagram.com/reel/demo-ai-agents',
    title: 'Instagram reel about AI agents as personal operators',
    creator: 'agentbuilder.daily',
    rawContent: 'Short reel explaining agents that remember projects, preferences, and repeated workflows.',
    transcript: '',
    extractedText: '',
    summary: 'A saved social post about AI agents that act from personal memory instead of blank prompts.',
    reasonSaved: 'Useful framing for Recall as an agent brain.',
    userNote: 'Avoid creepy clone language. Make it evidence based.',
    tags: ['demo', 'agent-brain', 'social'],
    topics: ['AI agents', 'personal memory', 'automation'],
    values: ['Autonomy', 'Usefulness'],
    emotions: ['curiosity', 'momentum'],
    aesthetics: ['fast cuts', 'clean captions'],
    people: [],
    tools: ['AI agents'],
    projects: ['Recall', 'MazOS'],
    traitsSuggested: ['system builder', 'practical futurist'],
    importanceScore: 88,
    profileImpactScore: 84,
    confidence: 0.84,
    status: 'added_to_profile',
    sensitive: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mem_discipline_lecture',
    userId,
    type: 'video',
    platform: 'youtube',
    sourceUrl: 'https://youtube.com/watch?v=discipline',
    title: 'YouTube lecture on discipline, sincerity, and intention',
    creator: 'Islamic learning channel',
    rawContent: '',
    transcript: 'A lecture about sincerity, discipline, restraint, and building habits for the sake of Allah.',
    extractedText: '',
    summary: 'A spiritual lecture connecting disciplined habits with sincerity and long-term character.',
    reasonSaved: 'Reminder that systems need an ethical center.',
    userNote: 'This should inform the values map, not become public content.',
    tags: ['demo', 'spiritual', 'discipline'],
    topics: ['discipline', 'sincerity', 'habits'],
    values: ['Sincerity', 'Self-mastery', 'Service'],
    emotions: ['conviction', 'reflection'],
    aesthetics: ['plain lecture', 'calm speech'],
    people: ['speaker'],
    tools: [],
    projects: ['Islamic learning', 'health/discipline'],
    traitsSuggested: ['values-led', 'self-correcting'],
    importanceScore: 91,
    profileImpactScore: 89,
    confidence: 0.87,
    status: 'added_to_profile',
    sensitive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mem_founder_podcast',
    userId,
    type: 'audio',
    platform: 'web',
    sourceUrl: 'https://podcast.example/founder-autonomy',
    title: 'Podcast about entrepreneurship and autonomy',
    creator: 'Founder Notes',
    rawContent: '',
    transcript: 'Discussion about small teams, profitable tools, speed, and independent ownership.',
    extractedText: '',
    summary: 'A podcast episode about building owned products instead of depending on gatekeepers.',
    reasonSaved: 'Matches desire for independence and useful tools.',
    userNote: '',
    tags: ['demo', 'business'],
    topics: ['entrepreneurship', 'ownership', 'small products'],
    values: ['Autonomy', 'Craft', 'Leverage'],
    emotions: ['drive'],
    aesthetics: ['direct conversation'],
    people: ['founder'],
    tools: ['Stripe', 'Vercel'],
    projects: ['JobFilter', 'personal finance'],
    traitsSuggested: ['builder mindset'],
    importanceScore: 78,
    profileImpactScore: 73,
    confidence: 0.78,
    status: 'processed',
    sensitive: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mem_dashboard_screenshot',
    userId,
    type: 'screenshot',
    platform: 'manual',
    title: 'Screenshot of a beautiful calm dashboard UI',
    creator: 'unknown',
    rawContent: '',
    transcript: '',
    extractedText: 'Dark interface, thin lines, dense cards, memory graph, evidence sidebar, export controls.',
    summary: 'A visual reference for a private, calm, high-signal dashboard.',
    reasonSaved: 'This is close to the feel Recall should have.',
    userNote: 'Use calm future OS, not corporate SaaS.',
    tags: ['demo', 'visual-taste'],
    topics: ['dashboard design', 'private OS'],
    values: ['Clarity', 'Control'],
    emotions: ['focus'],
    aesthetics: ['dark glass', 'thin borders', 'dense layout', 'quiet accent'],
    people: [],
    tools: ['UI system'],
    projects: ['Recall'],
    traitsSuggested: ['taste-driven builder'],
    importanceScore: 82,
    profileImpactScore: 77,
    confidence: 0.82,
    status: 'added_to_profile',
    sensitive: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mem_local_ai_repo',
    userId,
    type: 'github',
    platform: 'github',
    sourceUrl: 'https://github.com/example/local-ai-tools',
    title: 'GitHub repo about local AI tools',
    creator: 'open-source maintainer',
    rawContent: 'Local embeddings, private document search, model adapters, and MCP server examples.',
    transcript: '',
    extractedText: '',
    summary: 'A repo with building blocks for private local AI memory and context servers.',
    reasonSaved: 'Technical path for local-first Recall.',
    userNote: '',
    tags: ['demo', 'github', 'local-ai'],
    topics: ['local AI', 'MCP', 'embeddings'],
    values: ['Privacy', 'Ownership', 'Technical leverage'],
    emotions: ['possibility'],
    aesthetics: ['developer tools'],
    people: [],
    tools: ['MCP', 'embeddings', 'local LLM'],
    projects: ['Recall', 'coding/tools'],
    traitsSuggested: ['technical systems thinker'],
    importanceScore: 86,
    profileImpactScore: 83,
    confidence: 0.86,
    status: 'processed',
    sensitive: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mem_mazos_note',
    userId,
    type: 'note',
    platform: 'manual',
    title: 'Manual note about building MazOS',
    creator: 'demo user',
    rawContent: 'MazOS should turn chaos into calm systems: memory, projects, discipline, agents, and daily action.',
    transcript: '',
    extractedText: '',
    summary: 'A personal note about building an operating system for projects, memory, and discipline.',
    reasonSaved: 'This is one of the core life/project directions.',
    userNote: 'Recall can become the memory layer underneath it.',
    tags: ['demo', 'mazos'],
    topics: ['personal OS', 'systems', 'discipline'],
    values: ['Order', 'Autonomy', 'Service'],
    emotions: ['urgency', 'clarity'],
    aesthetics: ['operating system', 'command center'],
    people: [],
    tools: ['agents', 'Obsidian'],
    projects: ['MazOS', 'Recall'],
    traitsSuggested: ['turns chaos into systems'],
    importanceScore: 94,
    profileImpactScore: 94,
    confidence: 0.9,
    status: 'added_to_profile',
    sensitive: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mem_pkm_article',
    userId,
    type: 'url',
    platform: 'web',
    sourceUrl: 'https://example.com/personal-knowledge-management',
    title: 'Article about personal knowledge management',
    creator: 'PKM writer',
    rawContent: 'PKM systems work when they compound into decisions, projects, and future context.',
    transcript: '',
    extractedText: '',
    summary: 'An article arguing that notes should become decisions and project context.',
    reasonSaved: 'Recall should move beyond storage into action.',
    userNote: '',
    tags: ['demo', 'pkm'],
    topics: ['knowledge management', 'project memory'],
    values: ['Clarity', 'Compounding'],
    emotions: ['recognition'],
    aesthetics: ['structured writing'],
    people: [],
    tools: ['Obsidian'],
    projects: ['Recall', 'Obsidian'],
    traitsSuggested: ['context keeper'],
    importanceScore: 76,
    profileImpactScore: 72,
    confidence: 0.77,
    status: 'processed',
    sensitive: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mem_community_post',
    userId,
    type: 'social',
    platform: 'instagram',
    sourceUrl: 'https://instagram.com/p/community-work',
    title: 'Saved post about community work',
    creator: 'community builder',
    rawContent: 'Local community projects need trust, consistency, and service before scale.',
    transcript: '',
    extractedText: '',
    summary: 'A saved post about building trust through consistent community service.',
    reasonSaved: 'Connects product work with benefit beyond self.',
    userNote: '',
    tags: ['demo', 'community'],
    topics: ['community', 'trust', 'service'],
    values: ['Service', 'Trust', 'Consistency'],
    emotions: ['responsibility'],
    aesthetics: ['human stories'],
    people: [],
    tools: [],
    projects: ['Zawiyah/community'],
    traitsSuggested: ['community-oriented'],
    importanceScore: 79,
    profileImpactScore: 75,
    confidence: 0.8,
    status: 'processed',
    sensitive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mem_bad_habits_video',
    userId,
    type: 'video',
    platform: 'tiktok',
    sourceUrl: 'https://tiktok.com/@demo/video/bad-habits',
    title: 'Video about quitting bad habits',
    creator: 'discipline creator',
    rawContent: '',
    transcript: 'Small environment changes make discipline easier than relying on emotion.',
    extractedText: '',
    summary: 'A short video about designing environments that make bad habits harder.',
    reasonSaved: 'Practical habit design.',
    userNote: '',
    tags: ['demo', 'habits'],
    topics: ['habits', 'discipline', 'environment design'],
    values: ['Self-mastery', 'Practicality'],
    emotions: ['resolve'],
    aesthetics: ['short direct advice'],
    people: [],
    tools: [],
    projects: ['health/discipline'],
    traitsSuggested: ['action-oriented'],
    importanceScore: 74,
    profileImpactScore: 69,
    confidence: 0.74,
    status: 'needs_context',
    sensitive: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoProfile: UserProfile = {
  id: 'profile_demo',
  userId,
  summary:
    'Your inputs suggest a builder trying to turn scattered digital life into calm systems, with strong interest in AI agents, discipline, autonomy, and service.',
  currentDirection:
    'Building a private personal intelligence layer that can power better assistants, project decisions, and daily action.',
  interests: ['AI agents', 'personal operating systems', 'knowledge management', 'discipline', 'faith-informed ethics', 'community work'],
  values: ['Autonomy', 'Privacy', 'Sincerity', 'Service', 'Clarity', 'Self-mastery'],
  beliefs: ['Useful AI should be grounded in evidence', 'Systems should support character instead of replacing it', 'Private context is more valuable than generic chat'],
  worldview: ['Technology should increase agency', 'Long-term projects need ethical constraints', 'Memory becomes useful when it changes action'],
  traits: ['system builder', 'practical futurist', 'values-led', 'direct communicator', 'self-correcting'],
  communicationStyle: ['direct', 'specific', 'high-signal', 'action-oriented'],
  humourStyle: ['dry', 'observational', 'uses contrast sparingly'],
  aestheticTaste: ['calm dark surfaces', 'thin borders', 'dense information', 'quiet futuristic controls'],
  contentTaste: ['practical prompts', 'founder lessons', 'spiritual reminders', 'systems thinking', 'local-first AI'],
  learningStyle: ['learns by building', 'collects references', 'prefers examples tied to projects'],
  decisionMakingStyle: ['moves fast after clear direction', 'uses constraints', 'returns to evidence'],
  productivityStyle: ['turn chaos into systems', 'capture first then refine', 'prefers direct next actions'],
  spiritualEthicalOrientation: ['sincerity', 'service', 'restraint', 'privacy', 'benefit over vanity'],
  goals: ['Build Recall into an agent brain', 'Ship useful tools', 'Improve discipline', 'Serve community', 'Own more of the data layer'],
  frictions: ['too many inputs', 'shifting product direction', 'over-collection without action', 'energy dips from scattered context'],
  habits: ['saving references', 'turning notes into systems', 'testing product ideas', 'collecting prompts'],
  emotionalPatterns: ['momentum around autonomy', 'reflection around sincerity', 'urgency around unfinished systems'],
  contradictions: ['wants calm systems but repeatedly captures chaotic inputs', 'values privacy while exploring social-platform imports'],
  recurringThemes: ['agent brain', 'personal OS', 'discipline', 'privacy', 'community benefit', 'turning chaos into systems'],
  projectObsessions: ['Recall', 'MazOS', 'JobFilter', 'Obsidian workflow'],
  influences: ['AI agent builders', 'Islamic lecturers', 'indie founders', 'local-first tooling'],
  blindSpots: ['May collect more evidence than is needed before acting', 'May over-scope products before the core loop is proven'],
  confidence: 0.82,
  evidenceMemoryIds: demoMemoryItems.slice(0, 6).map((item) => item.id),
  version: 3,
  updatedAt: now,
};

export const demoInsights: ProfileInsight[] = [
  {
    id: 'insight_chaos_to_systems',
    userId,
    type: 'pattern',
    title: 'You keep turning chaos into systems',
    description:
      'Across AI agents, MazOS, PKM, and habit content, the repeated move is capture, structure, action.',
    evidenceMemoryIds: ['mem_ai_agents_reel', 'mem_mazos_note', 'mem_pkm_article'],
    confidence: 0.9,
    suggestedAction: 'Make Recall process one saved input into one useful action before adding more integrations.',
    createdAt: now,
  },
  {
    id: 'insight_privacy_tension',
    userId,
    type: 'contradiction',
    title: 'Privacy and social imports need explicit boundaries',
    description:
      'The product wants rich personal context, but the framing must stay user-provided, consent-based, and exportable.',
    evidenceMemoryIds: ['mem_ai_agents_reel', 'mem_local_ai_repo', 'mem_community_post'],
    confidence: 0.84,
    suggestedAction: 'Keep social capture limited to pasted links, exports, and future authorised connectors.',
    createdAt: now,
  },
  {
    id: 'insight_agent_context',
    userId,
    type: 'agent_context',
    title: 'Coding agents need your product principles up front',
    description:
      'Your saved references repeatedly show a preference for direct action, evidence, privacy, and calm UI.',
    evidenceMemoryIds: ['mem_dashboard_screenshot', 'mem_local_ai_repo', 'mem_mazos_note'],
    confidence: 0.86,
    suggestedAction: 'Generate Codex/OpenCode/Hermes prompts from the current profile version.',
    createdAt: now,
  },
];

export const demoTasteNodes: TasteNode[] = [
  {
    id: 'taste_visual_calm_os',
    userId,
    category: 'visual taste',
    label: 'Calm private OS',
    description: 'Dark surfaces, precise lines, dense but quiet information, little marketing gloss.',
    evidenceMemoryIds: ['mem_dashboard_screenshot', 'mem_mazos_note'],
    strength: 91,
    confidence: 0.86,
  },
  {
    id: 'taste_content_practical_agents',
    userId,
    category: 'content taste',
    label: 'Practical agent systems',
    description: 'Content that turns AI concepts into concrete workflows, prompts, and tools.',
    evidenceMemoryIds: ['mem_ai_agents_reel', 'mem_local_ai_repo'],
    strength: 88,
    confidence: 0.84,
  },
  {
    id: 'taste_lecture_sincerity',
    userId,
    category: 'speaker/lecture taste',
    label: 'Sincerity and self-mastery',
    description: 'Lectures that connect discipline to intention, restraint, and service.',
    evidenceMemoryIds: ['mem_discipline_lecture', 'mem_bad_habits_video'],
    strength: 84,
    confidence: 0.82,
  },
];

export const demoIntentNodes: IntentNode[] = [
  {
    id: 'intent_build_agent_brain',
    userId,
    inferredIntent: 'Build a private agent brain from personal evidence',
    relatedGoal: 'Make future AI assistants start with structured personal context',
    relatedProject: 'Recall',
    relatedMemoryIds: ['mem_ai_agents_reel', 'mem_local_ai_repo', 'mem_mazos_note'],
    suggestedAction: 'Ship the capture -> memory item -> profile insight -> agent prompt loop.',
    confidence: 0.9,
  },
  {
    id: 'intent_spiritual_discipline',
    userId,
    inferredIntent: 'Create discipline systems that stay ethically grounded',
    relatedGoal: 'Use systems to reinforce sincerity and self-mastery',
    relatedProject: 'health/discipline',
    relatedMemoryIds: ['mem_discipline_lecture', 'mem_bad_habits_video'],
    suggestedAction: 'Generate a weekly reflection prompt from sensitive memories without exporting them by default.',
    confidence: 0.82,
  },
];

export const demoProjects: Project[] = [
  {
    id: 'project_recall',
    userId,
    name: 'Recall',
    description: 'User-owned personal intelligence layer and agent memory operating system.',
    relatedMemoryIds: ['mem_ai_agents_reel', 'mem_dashboard_screenshot', 'mem_local_ai_repo', 'mem_pkm_article'],
    themes: ['agent brain', 'privacy', 'memory graph', 'profile evidence'],
    nextActions: ['Prove the capture pipeline', 'Generate useful agent prompts', 'Add Obsidian export', 'Design MCP context pack'],
    agentPrompts: ['Codex product reset prompt', 'Research agent market map', 'Reflection agent weekly digest'],
    status: 'active',
  },
  {
    id: 'project_mazos',
    userId,
    name: 'MazOS',
    description: 'Personal operating system for projects, habits, memory, and agents.',
    relatedMemoryIds: ['mem_mazos_note', 'mem_ai_agents_reel'],
    themes: ['personal OS', 'daily action', 'discipline'],
    nextActions: ['Define modules', 'Connect Recall profile', 'Create daily command view'],
    agentPrompts: ['Personal OS architect prompt'],
    status: 'watching',
  },
  {
    id: 'project_jobfilter',
    userId,
    name: 'JobFilter',
    description: 'Lead quality product that filters noise into useful customer action.',
    relatedMemoryIds: ['mem_founder_podcast'],
    themes: ['useful tools', 'direct revenue', 'automation'],
    nextActions: ['Protect lead scoring', 'Keep UI focused', 'Use Recall prompts for product decisions'],
    agentPrompts: ['Coding agent prompt for lead quality'],
    status: 'active',
  },
  {
    id: 'project_zawiyah',
    userId,
    name: 'Zawiyah/community',
    description: 'Community benefit and trust-building work, kept sensitive and private where required.',
    relatedMemoryIds: ['mem_community_post'],
    themes: ['service', 'trust', 'community'],
    nextActions: ['Keep private spiritual content out of digital systems', 'Track public operational tasks only'],
    agentPrompts: ['Community ops prompt without private instruction'],
    status: 'watching',
  },
];

export const demoPrompts: AgentPrompt[] = [
  {
    id: 'prompt_codex',
    userId,
    type: 'codex',
    title: 'Codex product builder context',
    basedOnProfileVersion: demoProfile.version,
    evidenceMemoryIds: ['mem_ai_agents_reel', 'mem_dashboard_screenshot', 'mem_local_ai_repo', 'mem_mazos_note'],
    createdAt: now,
    prompt:
      'Use evidence from Recall memory before coding. The user prefers direct action, privacy-first design, calm dense interfaces, and systems that turn chaotic inputs into useful next actions. Avoid agency/social-scraper framing.',
  },
  {
    id: 'prompt_reflection',
    userId,
    type: 'reflection_agent',
    title: 'Weekly reflection agent',
    basedOnProfileVersion: demoProfile.version,
    evidenceMemoryIds: ['mem_discipline_lecture', 'mem_bad_habits_video', 'mem_mazos_note'],
    createdAt: now,
    prompt:
      'Reflect on the week through evidence: discipline, sincerity, project momentum, and repeated frictions. Treat insights as suggestions, not fixed identity.',
  },
];

export const demoInstagramInbox: InstagramInboxProvision = {
  id: 'ig_inbox_demo_user',
  userId,
  mode: 'shared_recall_inbox',
  instagramHandle: 'recall.inbox',
  routingCode: 'RCL-MANAZ-9Q2',
  displayName: "Manaz's Recall Inbox",
  status: 'ready',
  setupSteps: [
    'Follow @recall.inbox',
    'Send posts, reels, screenshots, links, voice notes, or thoughts by DM',
    'Include RCL-MANAZ-9Q2 once so Recall routes the thread to the right account',
    'Reply with why you saved it when Recall asks for context',
  ],
  complianceNotes: [
    'Shared Recall-owned inbox with private routing code.',
    'No personal-account bot creation, impersonation, password collection, or scraping.',
    'Connected professional account mode can come later for creators and teams.',
  ],
  createdAt: now,
};

export const futureIntegrations = [
  'Instagram DM inbox capture',
  'Meta webhook verification',
  'Instagram thread routing codes',
  'browser extension capture',
  'Instagram export parser',
  'TikTok export/link enrichment',
  'YouTube transcript integration',
  'audio transcription',
  'image/screenshot OCR',
  'local LLM processing',
  'OpenAI/Anthropic/Gemini model adapter',
  'vector embeddings',
  'semantic search',
  'MCP server',
  'Obsidian sync',
  'mobile share sheet',
  'wearable data import',
  'private local-first mode',
  'encrypted storage',
  'agent API',
  'scheduled reflection digest',
  'profile version timeline',
  'multi-profile support',
  'agent context pack download',
];
